### ISSUE TITLE
statefulset.yaml template error

### ISSUE THREAD

**Issue by Zaijo** [p80n/photoprism-helm#6]
Hi. I ran into this error and as I am completely new to Help I don't know what else to do so I report it.

```
$ helm install photoprism p80n/photoprism --set persistence=false
Error: template: photoprism/templates/statefulset.yaml:71:28: executing "photoprism/templates/statefulset.yaml" at <.Values.persistence.volumeMounts>: can't evaluate field volumeMounts in type interface {}
```

Helm version 
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

**Comment by p80n** [comment]
This is also caused by the README example being out of date. I've updated it to reflect that it should be 
`--set persistence.enabled=false`.

**Comment by p80n** [comment]
If you continue to run into problems, feel free to open an issue.
