### ISSUE TITLE
Support for Kubernetes 1.22

### ISSUE THREAD

**Issue by rombert** [p80n/photoprism-helm#7]
With Kubernetes 1.22 the support for the `apiVersion: extensions/v1beta1` was removed for the Ingress object. This means that the chart will no longer install. I get errors along the lines of

> no matches for kind "Ingress" in version "extensions/v1beta1"

It would be great if the chart could be updated to support Kubernetes 1.22 or newer. I have little experience with Helm, but it seems that it's possible to support both version by using something like https://github.com/grafana/helm-charts/blob/eb15b43baa1d0ad5d63b56e906aa7eab2849477b/charts/grafana/templates/_helpers.tpl#L131-L142 .

**Comment by p80n** [comment]
Chart updated - please do a repo update and give it a shot :)

**Comment by rombert** [comment]
Thanks for the quick turnaround! I tested version 1.3.0 of the chart, and it still failed for me. IIUC the changes you made correctly, there is still support missing for the `networking.k8s.io/v1` API version. That is the only version that is now supported with Kubernetes 1.22+.

**Comment by p80n** [comment]
Sorry about that. There was a bit more to the ingress change than I first realized. Made another tweak. Note, if you've got a custom ingress config, you might need to define the new `path` and `pathType` parameters.
```  hosts:                                                                                                                                                                                                                           
  - host: my.domain.com                                                                                                                                                                                                            
    paths:                                                                                                                                                                                                                         
    - path: /                                                                                                                                                                                                                      
      pathtType: Prefix  ```

**Comment by rombert** [comment]
All good with helm chart version 1.3.1, thanks a lot for your support!
